### ISSUE TITLE
pass file path of template

### ISSUE THREAD

**Issue by nha** [davidsantiago/stencil#35]
Hello,

I am trying to use stencil, and I have a subdirectory of /templates containing various subfolders and mustache files ending in `.mu` from a legacy app.

Is there a way to render a file by passing the path to the file (including the file name, example "src/my_project/templates/subfolder/my_template.mu"), or am I doing domething wrong ?

As a side note, I found that using a configuration step (like in https://github.com/ryangreenhall/clj-jade#configuration) is very convenient. Maybe you could add that ?

Thanks

**Comment by davidsantiago** [comment]
Stencil will look for the templates on the classpath. Subdirectories and alternate file endings should work, as long as the templates are in the classpath and the path is relative to it.

**Comment by nha** [comment]
@davidsantiago Yes thank you I noticed that. I took me a bit of time to realise that I had not to include "src" in my path.
