### ISSUE TITLE
Prevent HTML-Escaping

### ISSUE THREAD

**Issue by Eschon** [davidsantiago/stencil#40]
I noticed that all the html that I try to add through variables gets escaped.
If I have a temlplate like this

``` HTML
...
<div>
  {{description}}
</div>
...
```

and data like this:

``` Clojure
...
:description "<p>This is HTML</p>"
...
```

The end result is

``` HTML
...
<div>
   &lt;p&gt;This is HTML&lt;p&gt;
</div>
...
```

Is there a way to prevent this from happening?

**Comment by davidsantiago** [comment]
Yes, use the unescaped mustache tag, which would be {{{description}}}.

**Comment by Eschon** [comment]
That works, thanks for the fast answer.
